USE DATABASE SWIGGY;

SELECT COUNT(*) AS users_count FROM RAW.USERS;
SELECT COUNT(*) AS restaurants_count FROM RAW.RESTAURANTS;
SELECT COUNT(*) AS food_count FROM RAW.FOOD;
SELECT COUNT(*) AS menu_count FROM RAW.MENU;
SELECT COUNT(*) AS orders_count FROM RAW.ORDERS;
SELECT COUNT(*) AS order_items_count FROM RAW.ORDER_ITEMS;
SELECT COUNT(*) AS reviews_count FROM RAW.REVIEWS;